version: '2'
services:
  app:
    build: .
    volumes:
      - ../:/app
    environment:
      NODE_ENV: development
    ports:
      - 9000:9000
    depends_on:
      - redis
  redis:
    image: redis:3-alpine
    ports:
      - "6379:6379"
